### ISSUE TITLE
Build error under Arch Linux

### ISSUE THREAD

**Issue by stefanhusmann** [varuna-lang/varuna#37]
The sources from git fail to compile under Arch Linux.

[ 71%] Building CXX object src/CMakeFiles/src.dir/CLI.cpp.o
/home/haawda/paketierung/meine_Pakete/varuna-git/src/varuna/src/CLI.cpp: In member function 'int CLI::run()':
/home/haawda/paketierung/meine_Pakete/varuna-git/src/varuna/src/CLI.cpp:44:27: error: could not convert 'CLI::showVersion' from 'void (*)()' to 'llvm::cl::VersionPrinterTy' {aka 'std::function<void(llvm::raw_ostream&)>'}
     cl::SetVersionPrinter(&showVersion);
                           ^~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/src.dir/build.make:63: src/CMakeFiles/src.dir/CLI.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:308: src/CMakeFiles/src.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by eliaskosunen** [comment]
First of all, it's really cool that you're trying out the project! Unfortunately, I haven't touched this in over a year, so breakages are bound to happen.

What comes to your error, it's caused by API-incompatibilities between LLVM versions. It seems like the signature of the callback required by `llvm::cl::SetVersionPrinter` has been changed from `void (*)()` to `std::function<void (llvm::raw_ostream&)>`. The latest LLVM version in pacman is [6.0](https://www.archlinux.org/packages/extra/x86_64/llvm/). That version is incompatible with 4.0, which is the version this project targeted. README was written back when pacman provided 4.0 by default, which probably misled you. Unfortunately, there's no easy way to get LLVM 4.0 binaries in Arch Linux, but you'd have to pull the sources and build it yourself.

There's really no way to make this work with LLVM 6.0, because porting would be a very sizable task, that I'm not willing to do at the moment.

Sorry for the inconvenience.

**Comment by stefanhusmann** [comment]
I now hav llvm40 and llvm40-libs installed, but the build system still finds llvm 6.0.0 first and uses this rather han searching for more suited versions. 

CMAKE tells me so:
-- Found LLVM 6.0.0
-- LLVM include directory: /usr/include
-- LLVM library directory: /usr/lib
-- Configuring done
-- Generating done

This did not change after I added 
	  -DLLVM_PACKAGE_VERSION=4.0.0 
and 
          -DLLVM_INCLUDE_DIRS=/usr/lib/llvm-4.0/include/
to the cmake call.

**Comment by eliaskosunen** [comment]
CMake variable `LLVM_DIR` is used to denote the LLVM installation directory. In your case it might be something like `-DLLVM_DIR=/usr/lib/llvm-4.0`, or something else depending on the location of your LLVM installation.

**Comment by stefanhusmann** [comment]
Hello, setting -DLLVM_DIR=/usr/lib/llvm-4.0 seems to work quite well for the core
-- Found LLVM 4.0.1
-- LLVM include directory: /usr/lib/llvm-4.0/include
-- LLVM library directory: /usr/lib/llvm-4.0/lib
-- Configuring done
-- Generating done
...
but the generated varuna-opt binary does not find the libLLVM-4.0.so file, which is located correctly at  
/usr/lib/llvm-4.0/lib/libLLVM-4.0.so.
